### PR TITLE
Getting a context complete URL

### PR DESCRIPTION
**Pull request by jiboule**
Allow the user to get the url of a context

### CODE REVIEW

**Comment by felixgilles** [comment]
Same that Tools_Url::context($context)

**Comment by jiboule** [comment]
The context() method doesn't return the same result as I need the url of a given context :(

**Comment by felixgilles** [comment]
This is the goal of  Tools_Url::context($context), to return the url of a given context

https://github.com/novius-os/core/blob/master/dubrovka/framework/classes/tools/url.php#L49

**Comment by jiboule** [comment]
Oh right, thanks and sorry, my bad !

**Pull request closed without merging**
