### PR TITLE
small tip to ensure avoid any cache

### PR DESCRIPTION
**Pull request by vrcAlbert**
Avoid cache (other than nOS cache).
This may not be the best way to do this, but it's a simple one.

### CODE REVIEW

**Comment by felixgilles** [comment]
We think that this is not the good solution to avoid browser cache
It's better to send headers that specify that this response has not to be cached

**Comment by vrcAlbert** [comment]
It's been a long time since writing this PR! I tried another option : is this one more acceptable?

**Comment by Foine** [comment]
Do set the "Expires" value at "0" is the same than set a date in the past ?

Anyway, it seems good to me. :+1:

**Comment by Savageman** [comment]
Looks perfect based on this answer: http://stackoverflow.com/questions/49547/making-sure-a-web-page-is-not-cached-across-all-browsers
:+1:

**Comment by felixgilles** [comment]
:+1:

**Pull request merged**
