### PR TITLE
Fixes the Model::behaviours method unable to find an extended behaviour

### PR DESCRIPTION
**Pull request by Seb-C**

### CODE REVIEW

**Review by Meroje — CHANGES_REQUESTED** [review]
You're breaking dot notation access of params

**Comment by Meroje** [comment]
What happens to the parent class which may be registered too on the model ?

**Comment by Seb-C** [comment]
I just fixed the first issue about the dot notation.

**Comment by Seb-C** [comment]
@Meroje Fixed.

**Review by Meroje — APPROVED** [review]

**Review by jguyomard — APPROVED** [review]

**Pull request merged**
