### PR TITLE
bugfix : test on menu when trying to acess eav properties

### PR DESCRIPTION
**Pull request by vrcAlbert**
As properties on menu items mainly are eav, we need to check if those are set.

### CODE REVIEW

**Comment by Foine** [comment]
It seems an important add to me. Thank you ! :)
:+1:

**Comment by jguyomard** [comment]
:+1:

**Comment by Foine** [comment]
Can you just correct the space that scrutunizer don't like ?
https://scrutinizer-ci.com/g/novius-os/core/inspections/f124fc92-2d0c-4322-872c-2bf4f8dbc520/issues/files/framework/applications/noviusos_menu/views/driver/text.view.php?status=new&orderField=path&order=asc

Thank you in advance

**Comment by vrcAlbert** [comment]
Done :)

**Comment by Foine** [comment]
Thank you ! :)

**Pull request merged**
