### PR TITLE
Bugfix with turkish characters in cache suffix Handler

### PR DESCRIPTION
**Pull request by jguyomard**
We have an issue with the cache "GET suffix handler" with turkish characters, resulting in incorrect file name on some systems.

### CODE REVIEW

**Comment by Seb-C** [comment]
:+1: but isn't `urlencode`ing useless now that it only contains alphanumerical characters ?

**Comment by jguyomard** [comment]
@Seb-C : i think using urlencode is safer, according to reply like this : http://stackoverflow.com/a/19931688

**Comment by smeeckaert** [comment]
What happens if the $_GET[$key] is in fact an array ? This protection seems to have been removed.

**Comment by jguyomard** [comment]
oops, well seen!

**Pull request merged**
