### PR TITLE
Allow to change Crud response when saving by using an Event

### PR DESCRIPTION
**Pull request by vrcAlbert**
what do you think of the name I've chosen for that event? Is it ok?

### CODE REVIEW

**Comment by Foine** [comment]
:+1:

**Comment by jguyomard** [comment]
"crudJson" => "afterSaveCrud" ?

**Comment by vrcAlbert** [comment]
Done :)

**Comment by jguyomard** [comment]
:+1:

**Comment by Foine** [comment]
:+1:

**Pull request merged**
