### PR TITLE
urlencode of virtual path

### PR DESCRIPTION
**Pull request by ghost**
Hello 

I've found a bug regarding the images.

When uploading an image using the Mediateque, if the image name contains a "+" simbol, then the virtual path will not be correctly built. An space will replace the "+", leading to a 404 error. Sometimes the user could chose to customize the url, including some bizarre characters.

In order to solve that issue, I have added the function urlencode in the method url() of the Model media.

### CODE REVIEW

**Review by Seb-C — APPROVED** [review]

**Comment by Meroje** [comment]
There may be a double encoding issue with toolkitImage https://github.com/novius-os/core/blob/203021392ace02d3c7239f36e5db20ca9f4b48f0/framework/classes/toolkit/image.php#L386

**Comment by ghost** [comment]
The encodePath method check whether the segment is encoded or not before actually encoding it:

novius-os/framework/classes/tools/url.php

` 
if (rawurldecode($segment) === $segment) {
    $path[$i] = rawurlencode($segment);
}
`

for instance I called this function and the string is already encoded:
'/cache/media/a%2B0rare/s,400,400-95bdaa.png" (%2B au lieu de +)'
This is the url retourned:
'/cache/media/a%2B0rare/s%2C400%2C400-95bdaa.png'

**Comment by tonyyb** [comment]
:+1:

**Comment by shaoshiva** [comment]
:+1:

**Comment by Meroje** [comment]
> The encodePath method check whether the segment is encoded or not before actually encoding it

fine then, maybe you could use it here too for consistency ?

**Comment by ghost** [comment]
Well you're right @Meroje my function url() return this:
media/products%2Fschemas%2Fa%2B0ra-re%2B.png -> The slash is replace by %2F by urlencode()

While my tests worked fine even if the slash was encoded, a much more clean result would be: 
media/products/schemas/a%2B0ra-re%2B.png -> Only the file name is encoded.

To get that (following @jguyomard idea, just in case you blame me xD) we reuse the function encodePath() which performs an ulr parsing by slash and encode the segment only if it was not already encoded. We slightly modifie the method signature to get the complete only when needed, to avoid that:

http://xxx-local.nosyyy.fr/http://xxx-local.nosyyy.fr/media/logofooter.jpg

and in this case, with $absolute = false, get that: 

media/products/schemas/a%2B0ra-re%2B.png

**Review by Meroje — APPROVED** [review]

**Review by shaoshiva — APPROVED** [review]

**Pull request merged**
